spring:
  application:
    name: book-store-v2
  datasource:
    username: postgres
    password: 1
    url: jdbc:postgresql://localhost:5432/book_store_v2_db
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    enabled: true