app:
  image:
    bucket: images
  page:
    size:
      top_by_rating_books: 4
      top_by_circulation_books: 4
      page: 30
      reviews_page: 18
      reviews_slider: 10

spring:
  application:
    name: book-store-v2
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    enabled: true