--liquibase formatted sql

--changeset alex:1
CREATE TABLE warehouse
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    count int NOT NULL DEFAULT 0,
    book_id int REFERENCES book(id) NOT NULL
);