--liquibase formatted sql

--changeset alex:1

CREATE TABLE user_like
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_id int REFERENCES users(id),
    book_review_id int REFERENCES book_review(id),
    reaction varchar(10),
    is_reacted boolean DEFAULT false
)