--liquibase formatted sql

--changeset alex:1

CREATE TABLE category
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(32)
);

--changeset alex:2

ALTER TABLE book
ADD COLUMN category_id int REFERENCES category(id) NOT NULL