--liquibase formatted sql

--changeset alex:1
CREATE TABLE user_book
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_id int REFERENCES users(id),
    book_id int REFERENCES book(id),
    is_in_favorites boolean DEFAULT false,
    is_in_cart boolean DEFAULT false,
    UNIQUE (user_id,book_id)
)