--liquibase formatted sql

--changeset alex:1

CREATE TABLE users
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    username varchar(128) NOT NULL UNIQUE ,
    password varchar(256) NOT NULL,
    role varchar(64) NOT NULL DEFAULT 'user'
)