--liquibase formatted sql

--changeset alex:1

CREATE TABLE book_review
(
    id int GENERATED BY DEFAULT AS IDENTITY ,
    book_id int REFERENCES book(id),
    user_id int REFERENCES users(id),
    content text NOT NULL ,
    likes int DEFAULT 0,
    dislikes int DEFAULT 0
)