--liquibase formatted sql

--changeset alex:1
CREATE TABLE book
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    author varchar(64) NOT NULL ,
    rating int,
    price int CHECK ( price >= 0 ) NOT NULL ,
    is_in_favorites boolean DEFAULT false,
    is_in_cart boolean DEFAULT false,
    image_path text
)